### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by Guoleming** [ace19-dev/gvcnn#2]
Could you achieve the results of the paper?

**Comment by ace19-dev** [comment]
I can not answer 'yes' because the work has been paused for a while.

**Comment by Guoleming** [comment]
I want to ask a question
Will the FCN parameters be updated when the CNN parameters are updated?

**Comment by ace19-dev** [comment]
I think that fcn parameters being updated well. however As I mentioned before, this work is a in progress. it means need more work to complete.

Thanks for interest.

**Comment by ace19-dev** [comment]
Hi Guoleming.

I've fixed a lot of code.
If you don't mind, please check again.

Many thanks.
