### ISSUE TITLE
retrieval

### ISSUE THREAD

**Issue by thesmalll** [ace19-dev/gvcnn#3]
I want to use the retrieval method of this article, you seem to implement it, but there is no code in the retrieval file.

**Comment by ace19-dev** [comment]
i'm sorry, this works is in verification. you might see in soon. thanks

**Comment by ace19-dev** [comment]
> I want to use the retrieval method of this article, you seem to implement it, but there is no code in the retrieval file.

hi. thesmall. 
you can check retrieval module. i hope it is helpful to you. thanks
