### ISSUE TITLE
Would you give a more detail explanation for data preparation and train/test configuration?

### ISSUE THREAD

**Issue by Hwang64** [ace19-dev/gvcnn#4]
Would you please give a more detail explanation for data preparation and train/test configurations?
Thanks a lot!

**Comment by ace19-dev** [comment]
hi Hwang64,
could you please check .md file again?

thank for interest.

**Comment by Hwang64** [comment]
Thanks for response!
after training finishes, is the file "eval.py" used for testing as your another Repositories "mvcnn-tf" does?
Thanks a lot!

**Comment by ace19-dev** [comment]
Yes, that's right. 

thanks
