### ISSUE TITLE
hello! I have questions about your code! 

### ISSUE THREAD

**Issue by nanjingyige** [ace19-dev/gvcnn#6]
I am wondering the highest accuracy of your code on ModelNet 40. Could your share the detailed information?

**Comment by ace19-dev** [comment]
Hi nanjingyige.
thanks for your interesting.

I am not sure because I did not compare exactly.and I would appreciate to think of this repository as one of the ways to implement gvcnn.

thanks.

**Comment by ace19-dev** [comment]
thanks for your interesting.
