### ISSUE TITLE
No learning progress with ModelNet10 data

### ISSUE THREAD

**Issue by tobinick-upb** [ace19-dev/gvcnn#7]
Hi,

i just tried to train the gvcnn model using the standard steps you expained. I downloaded the modelnet10 data, used data_utils for .png creation and dataset_tools for the creation of tfrecord.

For training I used the standard settings from train.py but also after two days of training there is no learning progress at all. Is there anything special to consider?

Best regards,
Tobi

**Comment by ace19-dev** [comment]
Hi Tobi. 

I am currently looking for a problem that needs improvement. it will be required some time.
Thank you for your interest.

**Comment by ace19-dev** [comment]
> Hi,
> 
> i just tried to train the gvcnn model using the standard steps you expained. I downloaded the modelnet10 data, used data_utils for .png creation and dataset_tools for the creation of tfrecord.
> 
> For training I used the standard settings from train.py but also after two days of training there is no learning progress at all. Is there anything special to consider?
> 
> Best regards,
> Tobi

**Comment by ace19-dev** [comment]
Hi Toby.

I've fixed a lot of code.
If you don't mind, please check again.

Many thanks.

**Comment by tobinick-upb** [comment]
Hi,

thanks for the info, I will check that.

Best regards,
Tobi

Von: Sean Kim <notifications@github.com>
Gesendet: Donnerstag, 21. November 2019 17:12
An: ace19-dev/gvcnn-tf <gvcnn-tf@noreply.github.com>
Cc: tobinick-upb <tobinick@mail.upb.de>; Author <author@noreply.github.com>
Betreff: Re: [ace19-dev/gvcnn-tf] No learning progress with ModelNet10 data (#7)


Hi Toby.

I've fixed a lot of code.
If you don't mind, please check again.

Many thanks.
