### ISSUE TITLE
Error in eval.py class during validation with pretrained checkpoints

### ISSUE THREAD

**Issue by GTripathee** [ace19-dev/gvcnn#8]
Hello,
I was trying to validate the dataset with pre-trained checkpoints. But it seems like there is missing function in nets/model class which is being accessed by eval.py class.
 
I got the following error.
"AttributeError: module 'nets.model' has no attribute 'discrimination_score".

Is there something I am missing or else?

Thank you!

**Comment by ace19-dev** [comment]
Hi. GTripathee
when i modified gvcnn module a few month ago, i missed eval.py script.
so i have just edited that. (but not tested.)

thank for interest.

**Comment by GTripathee** [comment]
Hi,

The issue mentioned above was solved. Thank you for the immediate action.
But that file still contains further problem.
1) num_group should be defined

flags.DEFINE_integer('num_group', 12, 'number of groups')

2) In line 147,
batch_xs, batch_ys, _ = sess.run(next_batch)
should be replaced by
batch_xs, batch_ys= sess.run(next_batch)

3) and in line 108,
eval_data.Dataset()
should be replace by importing val_data, so
val_data.Dataset()


By this minor changes code runs (tested).

thank you!

**Comment by ace19-dev** [comment]
thanks for your kindly feedback.
