### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by jiangyanjavawin** [ace19-dev/gvcnn#9]
hello,thanks for your code.There is a question about filter = ['1','2','4','7','8','10'] in the train.py,i don't know what's that.Thank you for your reply.

**Comment by ace19-dev** [comment]
hi, jiangyanjavawin

If you search a word 'filter' in total source, you can understand the meaning of filter keyword.
it means that you can filter specific views in total multi-view datasets to train.

thanks.

**Comment by jiangyanjavawin** [comment]
Thank you for your reply.I have understood that,but now i have a new question,when i run train.py,occure this error 'Key: image/encoded. Can't parse serialized Example' at validate,I think the problem is my test tfrecord,but i check the photo of test rea same like train's.I don't know why.By the way,thank you for your code,it's very good,i learn more,thank you.

**Comment by ace19-dev** [comment]
thank for interest. 
good luck.
